### ISSUE TITLE
Exhibition checklist

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/her-brush#24]
Can this populate from the yaml files, or do I need to supply the content?

**Comment by 1000camels** [comment]
I am not sure what the checklist is? Can you show me?

**Comment by vhellstein** [comment]
Ideally, it would look something like this [https://www.denverartmuseum.org/en/her-brush-companion-guide-checklist](url). I don't think the images need to be as big on the screen as they are in that link, but just a list of all the objects in the exhibition (not all of them are illustrated in the various texts).

**Comment by 1000camels** [comment]
Ah, I understand now. I knew this was coming but I was expecting it to be named Collection or something like that.

The way Quire wants us to do this is by using the objects.yml and to individually create object pages like this: https://quire.getty.edu/docs-v0/collection-catalogues/

I can do that or I can do a generic layout like I just did for Image Catalog (https://denverartmuseum.github.io/her-brush/image-catalog/).

Because of your example above, I am wondering whether you want that as the only display or whether you want a list and then a single page for each object? Keep in mind the reason for creating separate pages is that you might have multiple figures for each object

**Comment by vhellstein** [comment]
@mpopke do you have a preference in this regard? I guess I need to figure out how many objects would have multiple views....I can work on that Wednesday too.

**Comment by 1000camels** [comment]
Another consideration is the ability to page through each object (as opposed to scroll).

Quire, unfortunately, wants you to order your objects as you create each page. On the one hand, it gives you more control over the design and layout of each object page, however it also requires a lot of markdown page creations, and the use of the weight to order, which I find a little cumbersome.

Depending on what you decide, I may try to construct some kind of autogenerated page view, as this will make it easier.
Do you think the order of the entries in objects.yml correspond to how you would order them or would they need to be ordered manually (ie, a metadata field) or alphabetically?

**Comment by mpopke** [comment]
I think creating a page per object is overkill, especially since most of the objects just have tombstone information and not extended label text. I like the idea of the image catalog page with just the images and their caption/credit line, but I wish it pulled from the objects.yml instead of figures.yml.

I think having a single image catalog page, ordered by section is what we want. Do you think it would be easier to create a page that automates that based on the objects.yml file, or would you rather have a markdown file with a bunch of figure shortcodes in it?

Either way, Valerie and I are going to make sure the objects.yml file is complete and in the right order, and that there are corresponding figures and images for each object. Once we've done that, the objects.yml file will have the full checklist in the correct order, and then I can either send you a list of object/figure ids that you can work with or you can derive one from that file.

Only slightly related sidebar: How hard would it be to add the `loading="lazy"` attribute to the img elements produced by figure shortcodes? It's not critical—not for our expected audience—but it's a question this proposed page raises.

**Comment by 1000camels** [comment]
I am going to build a shortcode that does exactly that.

Easy and done

**Comment by 1000camels** [comment]
I've set up a version: https://denverartmuseum.github.io/her-brush/exhibition/checklist/
I will sort it by section and display headings

**Comment by 1000camels** [comment]
I could also bring back deepzoom effect

**Comment by mpopke** [comment]
I like that page. That works really well.

I think we would want deepzoom on these images, but their current display size (when unzoomed) looks really good.

**Comment by vhellstein** [comment]
@mpopke  we need to check the order of this and make sure the order follows the sections. @1000camels we need to add section headings too...
