### ISSUE TITLE
Deployment issue with background images

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/her-brush#32]
@mpopke can you do me a favour.

Can you check out the latest code and then run bin/deploy.sh?
I want to see if you can get the correct url for the background-images in the hero images.
I have been working with @geealbers to resolve this and he is able to run quire site and get the correct image path.

**Comment by mpopke** [comment]
I'm getting the same behavior as you, but one thing I've noticed while testing is that the background images work when using quire preview, but do not when using quire site. The path is the same in both cases (img/figures/whatever.jpg instead of ../img/figures/whatever.jpg), but it works in preview mode. Makes me wonder if there's an environment variable set incorrectly somewhere.

**Comment by 1000camels** [comment]
This has been fixed, by adjusting a few templates to use absURL instead of relURL
